config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index]

  root 'documents#index'

  resources :reports, only: [:index, :show, :destroy, :update] do
    patch :cancel, on: :member
    resource :verification, only: [:create]
  end
  resources :signings, only: :destroy

  resources :documents, only: [:index, :show] do
    member do
      get :download
    end
    resource :exports, only: [:new, :create]
  end
  resources :deliver_documents, only: :index
  resources :search_documents, only: :index

  resources :attendances, only: [:new]

  resources :report_faxes, only: [:create]

  resource :template, except: [:destroy]

  #namespace :api, defaults: { format: :json } do
  #  resources :prints, only: [:index]
  #  resources :reports, only: [:create, :show]
  #end
  namespace :api do
    resources :prints, only: [:index], defaults: { format: :json }
    resources :reports, only: [:create, :update, :show]
  end

  resources :faxes, only: :create

  resources :prints, except: [:edit, :update] do
    get 'aborted', on: :collection
    get 'search', on: :collection
    get 'filter', on: :collection
  end
end

app/models/print.rb
# Keeps track of print jobs.
class Print < Delivery
  belongs_to :printer, -> { with_deleted }, required: true

  validates :fax_number,
    presence: true, fax: true, if: :belongs_to_fax_printer?

  before_validation :assign_fax_number, unless: :fax_number, if: :belongs_to_fax_printer?, on: :create
  before_validation :strip_nondigits_from_fax_number, if: :fax_number
  before_create :print, unless: :job_number

  class << self
    # Updates status of active print jobs.
    def update_active
      Printer.active.find_each do |printer|
        statuses_by_job_number = driver_class(printer).statuses(printer)
        printer.prints.active.find_each do |print|
          if status = statuses_by_job_number[print.job_number]
            print.update!(status: status)
          end
        end
      end
    end

    def fake_printing?
      !!@fake_printing
    end

    def fake_printing=(true_or_false)
      @fake_printing = true_or_false
    end

    def driver_class(printer)
      if fake_printing?
        self::TestDriver
      else
        printer.class == HylafaxPrinter ? self::HylafaxDriver : self::CupsDriver
      end
    end
  end

  def self.updated_today
    where('updated_at >= ?', DateTime.current.beginning_of_day)
  end

  def self.count_by_status
    counts = group(:status).count
    Hash[Print.statuses.map { |k,v| [k.to_sym, counts.fetch(v, 0)] }]
  end

  def self.search(params)
    result = all

    if params[:title].present?
      result = result.joins(:document).where('documents.title LIKE ?', "%#{params[:title]}%")
    end

    if params[:fax_number].present?
      result = result.where(fax_number: params[:fax_number])
    end

    if params[:created_since].present?
      range = Time.zone.parse(params[:created_since])..Time.zone.now
      result = result.where(created_at: range)
    end

    if [:fax_number, :title].all? { |p| params[p].blank? }
      result = none
    end

    result
  end

  delegate :title, :path, :content_type, to: :document

  def to_s
    title
  end

  private

  def print
    driver.run ? self.job_number = driver.job_number : false
  end

  # Helper class to strip down a search query string.
  class Query
    attr_reader :query

    def initialize(query)
      @query = query
    end

    def blank?
      fax_number.nil? && names.empty?
    end

    def fax_number
      words.find { |word| /\A\d{4,}\Z/ =~ word }
    end

    def names
      words.select { |word| /\A[[:alpha:]]+\Z/ =~ word }
    end

    private

    def words
      query ? query.split : []
    end
  end

  private

  def assign_fax_number
    self.fax_number = self.document.fax_number if self.document
  end

  def strip_nondigits_from_fax_number
    self.fax_number =
      self.fax_number.present? ? self.fax_number.gsub(/[^0-9]/, '') : nil
  end

  def belongs_to_fax_printer?
    printer && printer.is_fax_printer?
  end

  def driver
    @driver ||= driver_class.new(self)
  end

  def driver_class
    if self.class.fake_printing?
      self.class::TestDriver
    else
      printer.class == HylafaxPrinter ? self.class::HylafaxDriver : self.class::CupsDriver
    end
  end
end

app/models/print/cups_driver.rb
# Interface to CUPS.
class Print::CupsDriver
  attr_reader :print

  class << self
    # Returns hash of print job statuses by job id.
    def statuses(printer)
      Cups.all_jobs(printer.name).inject({}) do |memo, (job_number,cups_job)|
        memo[job_number] = convert_status(cups_job.fetch(:state))
        memo
      end
    end

    private

    def convert_status(status)
      case status.to_sym
      when :completed            then :completed
      when :aborted, :cancelled  then :aborted
      else                            :active
      end
    end
  end

  def initialize(print)
    @print = print
  end

  # Actually print via CUPS
  def run
    cups_job.print
  end

  # Returns job_number from cups_job if valid.
  def job_number
    cups_job.job_id == 0 ? nil : cups_job.job_id
  end

  private

  def cups_job
    @cups_job ||= build_cups_job
  end

  def build_cups_job
    cups_job = if printer.is_fax_printer?
      Cups::PrintJob.new(print.path, printer.name, 'phone' => fax_number)
    else
      Cups::PrintJob.new(print.path, printer.name, 'Duplex' => 'DuplexNoTumble')
    end
    cups_job.title = print.title if print.title
    cups_job
  end

  def fax_number
    [printer.dialout_prefix, print.fax_number].join
  end

  def printer
    print.printer
  end
end

app/models/print/hylafax_driver.rb
# Interface to HylaFAX
class Print::HylafaxDriver
  attr_reader :print, :job_number

  class << self
    def statuses(printer)
      HylaFAX.faxstat(
        host: printer.host,
        port: printer.port,
        user: printer.user,
        password: printer.password,
        passive: true).inject({}) do |memo, (job_number,status)|
          memo[job_number] = convert_status(status)
          memo
        end
    end

    private

    def convert_status(status)
      case status
        when :done   then :completed
        when :failed then :aborted
        else              :active
      end
    end
  end

  def initialize(print)
    @print = print
  end

  def run
    @job_number = HylaFAX.sendfax(
      host: printer.host,
      port: printer.port,
      user: printer.user,
      password: printer.password,
      dialstring: dialstring,
      document: print.path,
      passive: true)
  end

  private

  def printer
    print.printer
  end

  def dialstring
    [printer.dialout_prefix, print.fax_number].join
  end
end

app/models/print/test_driver.rb
# A fake driver for test & development.
class Print::TestDriver
  attr_reader :print

  class << self
    # Returns empty hash.
    def statuses(printer)
      {}
    end
  end

  def initialize(print)
    @print = print
  end

  # Does nothing and always returns true.
  def run
    true
  end

  # Returns random job id.
  def job_number
    rand(100_000..999_999)
  end
end

app/controllers/api/prints_controller.rb
module API
  class PrintsController < ApplicationController
    def index
      @prints = prints
    end

    private

    def prints
      Print.all
    end
  end
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  protect_from_forgery except: [:create]

  def index
    @prints = prints.active
  end

  def show
    print = Print.find(params[:id])
    send_file print.path, type: print.content_type
  end

  def create
    @print = Print.new(print_params)
    respond_to do |format|
      if @print.save
        flash[:notice] = 'Druckauftrag wird gesendet.'
        format.html { redirect_to(@print.document) }
        format.json { render json: 'OK', status: :created } #TODO: Return more infos about the new print!
      else
        format.html { render action: 'new' }
        format.json { render json: @print.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    print = Print.find(params[:id])
    print.destroy if print
    redirect_to aborted_prints_path
  end

  def new
    @print = Print.new
  end

  def aborted
    @prints = prints.aborted
    render :index
  end

  def search
    @prints = prints.search(params)
  end

  def filter
    @prints = prints.none # Return by default no prints

    # by fax_number
    if params[:fax_number]
      @prints = prints.where(fax_number: params[:fax_number])
    end

    # by creation time
    if params[:created]
      if params[:created].to_sym == :last_week
        @prints = @prints.created_last_week
      else
        @prints = prints.none
      end
    end
  end

  private

  def print_params
    params.require(:print).permit(:printer_id, :document_id)
  end

  def prints
    Print.all.order('updated_at DESC')
  end
end

app/helpers/prints_helper.rb
module PrintsHelper
  def aborted_prints_count
    count = Print.aborted.count
    count.zero? ? nil : count
  end

  def print_report_header
    timestamp = Time.zone.now.iso8601
    linelength = 66
    title = 'Fax-Bericht'
    title + timestamp.rjust(linelength-title.size)
  end

  def print_status_class(print)
    case print.status.to_sym
    when :active    then 'default'
    when :completed then 'success'
    when :aborted   then 'danger'
    end
  end
end

app/views/prints/_form.html.erb
<div class='container'>
<%= form_for(@print, html: { class: 'form-horizontal' }) do |f| %>
  <% if @print.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@print.errors.count, "error") %> prohibited this print from being saved:</h2>

      <ul>
      <% @print.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :title, class: 'control-label col-md-2' %>
    <div class='col-md-4'>
      <%= f.text_field :title, class: 'form-control', placeholder: 'Titel (z.B. Nachname, Vorname und Geb.-Datum)' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :fax_number, class: 'control-label col-md-2' %>
    <div class='col-md-4'>
      <%= f.text_field :fax_number, class: 'form-control', placeholder: 'Fax-Nummer (mit Vorwahl)' %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label :document, class: 'control-label col-md-2' %>
    <div class='col-md-4'>
      <%= f.file_field :document, class: 'form-control', accept: 'application/pdf' %>
    </div>
  </div>

  <%= f.submit 'Fax senden', class: 'btn btn-primary' %>
<% end %>
</div>

app/views/prints/_print.html.erb
<%= div_for(print, class: print.status) do %>
  <%= content_tag(:span, class: 'title') do %>
    <%= link_to print.title, print, target: '_blank' %>
  <% end %>
  <%= content_tag(:span, class: 'state') do %>
    <%= print.state %>
  <% end %>
<% end %>

app/views/prints/filter.html.erb
<div class='container'>
<h1>Fax-Bericht</h1>
<p>Erstellt: <%= Time.zone.now %></p>

<table>
  <tr>
    <th>Druckauftrag</th>
    <th>Empfänger</th>
    <th>Erstellt</th>
    <th>Status</th>
  </tr>
  <% @prints.each do |print| %>
    <%= content_tag_for(:tr, print, class: print.status) do %>
      <%= content_tag(:td, print.title, class: 'title') %>
      <%= content_tag(:td, print.fax_number, class: 'fax_number') %>
      <%= content_tag(:td, print.created_at.to_date, class: 'created_at') %>
      <%= content_tag(:td, print.status, class: 'status') %>
    <% end %>
  <% end %>
</table>
</div>

app/views/prints/index.html.erb
<ul class='nav nav-tabs'>
  <%= content_tag(:li, link_to('Aktive Druckaufträge', prints_path), class: ('active' if action_name == 'index')) %>
  <%= content_tag(:li, class: ('active' if action_name == 'aborted')) do %>
    <%= link_to(aborted_prints_path) do %>
      <%= content_tag(:span, 'Abgebrochene Druckaufträge') %>
      <%= content_tag(:span, aborted_prints_count, class: 'badge') %>
    <% end %>
  <% end %>
  <%= content_tag(:li, link_to('Suche', search_prints_path), class: ('active' if action_name == 'search')) %>
</ul>

<table>
  <tr>
    <th>Druckauftrag</th>
    <th>Empfänger</th>
    <th>Erstellt</th>
    <th>Status</th>
  </tr>
  <% @prints.each do |print| %>
    <%= content_tag_for(:tr, print, class: print.status) do %>
      <%= content_tag(:td, class: 'title') do %>
        <%= link_to(print.title, print, target: '_blank') %>
      <% end %>
      <%= content_tag(:td, print.fax_number, class: 'fax_number') %>
      <%= content_tag(:td, print.created_at, class: 'created_at') %>
      <%= content_tag(:td, print.status, class: 'status') %>
    <% end %>
  <% end %>
</table>

app/views/prints/new.html.erb
<h1>Neuer Druckauftrag</h1>

<%= render 'form' %>

app/views/prints/search.html.erb
<ul class='nav nav-tabs'>
  <%= content_tag(:li, link_to('Aktive Druckaufträge', prints_path), class: ('active' if action_name == 'index')) %>
  <%= content_tag(:li, link_to('Abgebrochene Druckaufträge', aborted_prints_path), class: ('active' if action_name == 'aborted')) %>
  <%= content_tag(:li, link_to('Suche', search_prints_path), class: ('active' if action_name == 'search')) %>
</ul>

<p>
Suche nach Geburtsdatum der Patientin (TT.MM.JJJJ), Name(n) oder Fax-Nummer des
Empfängers (min. 4 Ziffern) in beliebiger Kombination.
</p>

<%= form_tag(search_prints_path, method: :get) do %>
  <%= label_tag(:title, 'Suche:') %>
  <%= text_field_tag(:title, params[:title]) %>
  <%= submit_tag('Los gehts!', name: nil) %>
<% end %>

<table>
  <tr>
    <th>Druckauftrag</th>
    <th>Empfänger</th>
    <th>Erstellt</th>
    <th>Status</th>
  </tr>
  <% @prints.each do |print| %>
    <%= content_tag_for(:tr, print, class: print.status) do %>
      <%= content_tag(:td, class: 'title') do %>
        <%= link_to(print.title, print, target: '_blank') %>
      <% end %>
      <%= content_tag(:td, print.fax_number, class: 'fax_number') %>
      <%= content_tag(:td, print.created_at, class: 'created_at') %>
      <%= content_tag(:td, print.status, class: 'status') %>
    <% end %>
  <% end %>
</table>

app/views/prints/search.text.erb
<%= print_report_header %>
==================================================================
<%= "Empfänger:\t#{params[:fax_number]}\n" if params[:fax_number].present? -%>
<%= "Zeitraum:\t#{Time.zone.parse(params[:created_since]).to_s(:short)} - #{Time.zone.now.to_s(:short)}\n" if params[:created_since].present? -%>

Sendedatum<%= "\t" %>Patient(in) / Faxtitel
------------------------------------------------------------------
<% @prints.reorder(:created_at).each do |print| %>
<%= [print.created_at.strftime('%d.%m.%Y'), print.title].join("\t") %>
<% end %>


--
Radiologische Gemeinschaftspraxis im Evangelischen Krankenhaus Lippstadt
Wiedenbrücker Straße 33
59555 Lippstadt
Telefon: 02941 150 150
Fax: 02941 150 15 11