config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index]

  root 'documents#index'

  resources :reports, only: [:index, :show, :destroy, :update] do
    patch :cancel, on: :member
    resource :verification, only: [:create]
  end
  resources :signings, only: :destroy

  resources :documents, only: [:index, :show] do
    member do
      get :download
    end
    resource :exports, only: [:new, :create]
  end
  resources :deliver_documents, only: :index
  resources :search_documents, only: :index

  resources :attendances, only: [:new]

  resources :report_faxes, only: [:create]

  resource :template, except: [:destroy]

  #namespace :api, defaults: { format: :json } do
  #  resources :prints, only: [:index]
  #  resources :reports, only: [:create, :show]
  #end
  namespace :api do
    resources :prints, only: [:index], defaults: { format: :json }
    resources :reports, only: [:create, :update, :show]
  end

  resources :faxes, only: :create

  resources :prints, except: [:edit, :update] do
    get 'aborted', on: :collection
    get 'search', on: :collection
    get 'filter', on: :collection
  end
end

app/views/templates/_form.html.erb
<%= form_for(@template, url: template_path) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :short_title %><br>
    <%= f.text_field :short_title %>
  </div>
  <div class="field">
    <%= f.label :slogan %><br>
    <%= f.text_field :slogan %>
  </div>
  <div class="field">
    <%= f.label :return_address %><br>
    <%= f.text_field :return_address %>
  </div>
  <div class="field">
    <%= f.label :contact_infos %><br>
    <%= f.text_field :contact_infos %>
  </div>
  <div class="field">
    <%= f.label :owners %><br>
    <%= f.text_area :owners, cols: 25, rows: 4 %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/templates/_template.html.erb
<p>
  <strong>Title:</strong>
  <%= @template.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @template.subtitle %>
</p>

<p>
  <strong>Short title:</strong>
  <%= @template.short_title %>
</p>

<p>
  <strong>Slogan:</strong>
  <%= @template.slogan %>
</p>

<p>
  <strong>Return Address:</strong>
  <%= @template.return_address %>
</p>

<p>
  <strong>Contact Infos:</strong>
  <%= @template.contact_infos %>
</p>

<p>
  <strong>Owners:</strong>
  <%= @template.owners %>
</p>

app/views/templates/edit.html.erb
<h1>Vorlage bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Zurück', template_path %>

app/views/templates/new.html.erb
<h1>Neue Vorlage</h1>

<%= render 'form' %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Vorlage</h1>

<% if @template %>
  <%= render @template %>

  <%= link_to 'Vorlage bearbeiten', edit_template_path %>
<% else %>
  <%= link_to 'Neue Vorlage erstellen', new_template_path %>
<% end %>