config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index]

  root 'documents#index'

  resources :reports, only: [:index, :show, :destroy, :update] do
    patch :cancel, on: :member
    resource :verification, only: [:create]
  end
  resources :signings, only: :destroy

  resources :documents, only: [:index, :show] do
    member do
      get :download
    end
    resource :exports, only: [:new, :create]
  end
  resources :deliver_documents, only: :index
  resources :search_documents, only: :index

  resources :attendances, only: [:new]

  resources :report_faxes, only: [:create]

  resource :template, except: [:destroy]

  #namespace :api, defaults: { format: :json } do
  #  resources :prints, only: [:index]
  #  resources :reports, only: [:create, :show]
  #end
  namespace :api do
    resources :prints, only: [:index], defaults: { format: :json }
    resources :reports, only: [:create, :update, :show]
  end

  resources :faxes, only: :create

  resources :prints, except: [:edit, :update] do
    get 'aborted', on: :collection
    get 'search', on: :collection
    get 'filter', on: :collection
  end
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :recipient, required: true
  belongs_to :report
  has_many :prints
  has_many :deliveries
  has_many :exports

  has_attached_file :file,
    path: ':rails_root/storage/:rails_env/:class/:id/:attachment/:filename'

  validates_presence_of :title, unless: :report_id?
  validates_attachment_presence :file, unless: :report_id?
  validates_attachment_content_type :file, content_type: 'application/pdf'

  around_save :assign_report_attributes, if: :report_id?
  after_commit :deliver, on: [:update, :create], if: :to_deliver? # TODO: Test this!

  class << self
    def deliver(document_id)
      Document::Deliverer.new(find(document_id)).deliver
    end

    def delivered_today
      includes(:deliveries).
        where('deliveries.created_at > ?', Time.zone.now.beginning_of_day).
        order('deliveries.created_at DESC').distinct
    end

    def to_deliver
      released_for_delivery.without_active_or_completed_delivery
    end

    def released_for_delivery
      where("report_id is NULL OR #{Report.verified.where('reports.id = documents.report_id').exists.to_sql}")
    end

    def without_active_or_completed_delivery
      where(Delivery.active_or_completed.where('deliveries.document_id = documents.id').exists.not)
    end

    def search(query)
      if query[:title].present?
        result = all
        query[:title].split(' ').each do |word|
          result = result.where(arel_table[:title].matches("%#{word}%"))
        end
      else
        result = none
      end
      result
    end
  end

  delegate :path, :content_type, :fingerprint, to: :file
  delegate :fax_number, :send_with_hylafax?, to: :recipient

  def deliver
    DeliveryJob.perform_later(id)
  end

  def filename
    self.file_file_name
  end

  def to_deliver?
    released_for_delivery? && deliveries.active_or_completed.empty?
  end

  def delivered?
    deliveries.completed.present?
  end

  def released_for_delivery?
    report.blank? || report.verified?
  end

  def recipient_fax_number?
    recipient.fax_number?
  end

  def recipient_is_evk?
    !!(recipient.fax_number.match(/^0294167/) if recipient.fax_number?)
  end

  def report_pdf
    ReportPdf.new(self)
  end

  def assign_report_attributes
    report_pdf.to_file do |file|
      self.file  = file
      self.title = report.title
      yield
    end
  end
end

app/models/document/deliverer.rb
class Document::Deliverer
  attr_reader :document, :recipient

  def initialize(document)
    @document  = document
    @recipient = document.recipient
  end

  def deliver
    print_document
    export_document if document.recipient_is_evk?
  rescue StandardError => e
    Rails.logger.error(e.message)
  end

  def print_document
    document.prints.create(printer: printer)
  end

  def export_document
    document.exports.create(directory: directory) if directory
  end


  private

  def printer
    (if recipient.fax_number.present?
      recipient.send_with_hylafax? ? HylafaxPrinter : FaxPrinter
    else
      PaperPrinter
    end).default
  end

  def directory
    Directory.default
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :load_document, only: [ :show, :download ]
  before_action :load_documents, only: :index

  def index
  end

  def show
  end

  def download
    send_file @document.path, type: @document.content_type
  end

  private

  def load_document
    @document = Document.find(params[:id])
  end

  def load_documents
    @documents = Document.delivered_today
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def deliver_documents_count
    count = Document.to_deliver.count
    count.zero? ? nil : count
  end
end

app/views/documents/_documents.html.erb
<% if @documents.empty? %>
  <p class="lead">
    Nichts gefunden.
  </p>
<% else %>
  <div class="list-group">
    <% @documents.each do |document| %>
      <div class="list-group-item">
        <p class="list-group-item-heading">
          <%= link_to document, class: 'btn btn-default pull-right' do %>
            <span class="glyphicon glyphicon glyphicon-info-sign"></span>
            Details
          <% end %>
          <%= link_to document.title, download_document_path(document) %>
          <% if document.delivered? %>
            <span class="label label-success">gesendet</span>
          <% end %>
        </p>
        <p class="list-group-item-text">
          <%= l document.created_at %>
        </p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/documents/_header.html.erb
<ul id="documents_nav" class="nav nav-tabs">
  <li role="presentation" class='<%= 'active' if controller_name == 'documents' %>'>
    <%= link_to 'Heute', documents_path %>
  </li>
  <li role="presentation" class='<%= 'active' if controller_name == 'deliver_documents' %>'>
    <%= link_to(deliver_documents_path) do %>
      <%= content_tag(:span, 'Unerledigt') %>
      <%= content_tag(:span, deliver_documents_count, class: 'badge') %>
    <% end %>
  </li>
  <li role="presentation" class='<%= 'active' if controller_name == 'search_documents' %>'>
    <%= link_to 'Suche', search_documents_path %>
  </li>
</ul>

<% if controller_name == 'search_documents' %>
  <%= form_tag(search_documents_path, method: :get) do %>
    <%= label_tag(:title, 'Titel') %>
    <%= text_field_tag(:title, params[:title]) %>
    <%= submit_tag('Suchen', name: nil) %>
  <% end %>
<% end %>

app/views/documents/index.html.erb
<%= render 'header' %>
<%= render 'documents' %>

app/views/documents/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>
      Dokument: <%= @document.title %>
      <% if @document.delivered? %>
        <span class="label label-success">gesendet</span>
      <% end %>
    </h1>

    <%= link_to 'Zum Bericht', @document.report if @document.report %>

    <%= render @document.recipient %>


    <div class="btn-group">
      <%= link_to 'Herunterladen', download_document_path(@document), class: 'btn btn-default' %>
      <% if @document.released_for_delivery? %>
        <% if @document.recipient_fax_number? && fax_printer = (@document.send_with_hylafax? ? HylafaxPrinter : FaxPrinter).default %>
          <%= button_to 'Faxen', prints_path, method: :post,
            params: { 'print[printer_id]' => fax_printer.id, 'print[document_id]' => @document.id },
            class: 'btn btn-primary' %>
        <% end %>
        <% if paper_printer = PaperPrinter.default %>
          <%= button_to 'Drucken', prints_path, method: :post,
            params: { 'print[printer_id]' => paper_printer.id, 'print[document_id]' => @document.id },
            class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <% if @document.prints.present? %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <div class="panel-title">
            <%= Print.model_name.human(count: @document.prints.count) %>
          </div>
        </div>
        <table class="table">
          <tr>
            <th>
              <%= Print.human_attribute_name(:created_at) %>
            </th>
            <th>
              <%= Printer.model_name.human %>
            </th>
            <th>
              <%= Print.human_attribute_name(:fax_number) %>
            </th>
            <th>
              <%= Print.human_attribute_name(:status) %>
            </th>
          </tr>
          <% @document.prints.order(:created_at).each do |print| %>
            <tr class="<%= print_status_class(print) %>">
              <td>
                <%= l print.created_at %>
              </td>
              <td>
                <%= print.printer.name %>
              </td>
              <td>
                <%= print.fax_number %>
              </td>
              <td>
                <%= t print.status, scope: 'activerecord.attributes.print.statuses' %>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    <% else %>
      <p class="lead">
        Hoppla, zu diesem Dokument gibt es noch keine Druckaufträge.
      </p>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= render 'exports/panel' %>
  </div>
</div>