config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :users, only: [:index]

  root 'documents#index'

  resources :reports, only: [:index, :show, :destroy, :update] do
    patch :cancel, on: :member
    resource :verification, only: [:create]
  end
  resources :signings, only: :destroy

  resources :documents, only: [:index, :show] do
    member do
      get :download
    end
    resource :exports, only: [:new, :create]
  end
  resources :deliver_documents, only: :index
  resources :search_documents, only: :index

  resources :attendances, only: [:new]

  resources :report_faxes, only: [:create]

  resource :template, except: [:destroy]

  #namespace :api, defaults: { format: :json } do
  #  resources :prints, only: [:index]
  #  resources :reports, only: [:create, :show]
  #end
  namespace :api do
    resources :prints, only: [:index], defaults: { format: :json }
    resources :reports, only: [:create, :update, :show]
  end

  resources :faxes, only: :create

  resources :prints, except: [:edit, :update] do
    get 'aborted', on: :collection
    get 'search', on: :collection
    get 'filter', on: :collection
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Faxomat</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class='container'>
    <nav class='navbar navbar-default'>
      <div id='navbar' class='navbar-collapse collapse'>
        <% if user_signed_in? %>
          <ul class='nav navbar-nav navbar-left'>
            <li class="<%= 'active' if controller_name =~ /documents$/ %>">
              <%= link_to 'Versendungen', documents_path %>
            </li>
            <li class="<%= 'active' if controller_name == 'reports' %>">
              <%= link_to 'Arztbriefe', reports_path %>
            </li>
          </ul>

          <ul class='nav navbar-nav navbar-right'>
            <li>
              <%= link_to current_user.username, edit_user_registration_path(current_user) %>
            </li>
            <li>
              <%= link_to 'Abmelden', destroy_user_session_path, method: :delete %>
            </li>
          </ul>
        <% else %>
          <ul class='nav navbar-nav navbar-right'>
            <li>
              <%= link_to 'Anmelden', new_user_session_path %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>

    <div class="row">
      <div class="col-xs-12">
        <%= bootstrap_flash %>
      </div>
    </div>

    <%= yield %>
  </div>

</body>
</html>